# Travis setup taken from: https://github.com/ankurk91/phpunit-travis-ci-coverage-example/blob/master/.travis.yml

# Config file for https://travis-ci.org/
# Validate this file here - http://lint.travis-ci.org/

language: php

# Define the php versions against we want to test our code
php:
    - 7.1
    - 7.2

# Note: Code coverage requires php-xDebug extension enabled on CI server

install:
  # Install composer packages
  - travis_retry composer install --no-interaction --no-suggest
  # Install coveralls.phar
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar -O coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

# Create a storage folder for coverage report
before_script:
    - mkdir -p build/logs
    - ls -al

# Testing the app (see phpunit.xml) for configs, generating Code Coverage report
script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml


#after_script:


after_success:
# Submit coverage report to Coveralls servers, see .coveralls.yml
 - travis_retry php coveralls.phar -v
# Submit coverage report to codecov.io
 - bash <(curl -s https://codecov.io/bash)

#after_failure:

# Tell Travis CI to monitor only 'master' branch
branches:
  only: master

# You can delete the cache using travis-ci web interface
cache:
  directories:
  - vendor
  - $HOME/.cache/composer